AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: On demand image resizing AWS Lambda function.
Resources:
  ImageResizeOnDemand:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs16.x
      MemorySize: 1536
      Timeout: 60

  ImageResizeOnDemandPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ImageResizeOnDemand
      Action: lambda:InvokeFunction
      Principal: "arn:aws:iam::978552873556:user/texpert"
