AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: On demand image resizing AWS Lambda function.

Resources:
  ImageResizeOnDemand:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 1536
      Timeout: 60

  ResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ImageResizeOnDemand
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*
